# Generated by Django 3.1.7 on 2021-03-24 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lor_accounts', '0001_initial'),
        ('decks', '0002_auto_20210322_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_outcome', models.CharField(max_length=8)),
                ('order_of_play', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lor_accounts.loraccount')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.deck')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=128)),
                ('game_mode', models.CharField(max_length=32)),
                ('game_type', models.CharField(max_length=32)),
                ('game_start_time', models.DateTimeField()),
                ('game_version', models.CharField(max_length=32)),
                ('turn_count', models.IntegerField()),
                ('players', models.ManyToManyField(to='matches.MatchPlayer')),
            ],
        ),
    ]
