# Generated by Django 3.1.7 on 2021-03-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='language',
            field=models.CharField(default='en_us', max_length=32),
            preserve_default=False,
        ),
    ]
